# Deep Learning from Scratch

## Chap. 1: hello python
Reviewing numpy(1.5)

In [3]:
# import something as ~~
import numpy as np

In [4]:
# Making numpy array
x = np.array([1.0, 2.0, 3.0])
print(x)
print("type of numpy array x : ", type(x))

[1. 2. 3.]
type of numpy array x :  <class 'numpy.ndarray'>


* Arithmetic operation between numpy arrays(element-wise)

* Operation between different shapes(broadcast)

In [5]:
x = np.array([1.0, 2.0, 3.0])
y= np.array([2.0, 4.0, 6.0])

# Element-wise arithmetic operation
print("x + y = ", x + y)
print("x - y = ", x - y)
print("x * y = ", x * y)
print("x / y = ", x / y)

# Broadcast(numpy array, single scalar)
print("x / 2.0 = ", x / 2.0)

x + y =  [3. 6. 9.]
x - y =  [-1. -2. -3.]
x * y =  [ 2.  8. 18.]
x / y =  [0.5 0.5 0.5]
x / 2.0 =  [0.5 1.  1.5]


* Can make N-dim array with numpy
    * 1-dim array = vector 
    * 2-dim array = matrix
    * Generalized vectors, matrix = tensor 

In [16]:
# N-dim numpy array

A = np.array([[1, 2], [3, 4]])
print(A)
print("Shape of A: ", A.shape)
print("Data type of A: ", A.dtype)

# Element-wise operations with same shape
B = np.array([[3, 0], [0, 6]])
print("A + B = ", A + B)
print("A * B = ", A * B)

# Broadcast(2-dim array, single scalar)
print("A * 10 = ", A * 10)

# Broadcast(2-dim array, 1-dim array)
C = np.array([10, 20])
print("A * C = ", A * C)

[[1 2]
 [3 4]]
Shape of A:  (2, 2)
Data type of A:  int32
A + B =  [[ 4  2]
 [ 3 10]]
A * B =  [[ 3  0]
 [ 0 24]]
A * 10 =  [[10 20]
 [30 40]]
A * C =  [[10 40]
 [30 80]]


In [19]:
# Access to element of numpy array
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
print("Elements of 0th row: ", X[0])
print("Element of 0th row, 1th column: ", X[0][1])

[[51 55]
 [14 19]
 [ 0  4]]
Elements of 0th row:  [51 55]
Element of 0th row, 1th column:  55
[51 55]
[14 19]
[0 4]


In [20]:
# Can access each element by using for
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [26]:
# Can access multiple elements by flattens array
X_flat = X.flatten()
print(X_flat)
print("Elements of index 0, 2, 4: ", X_flat[np.array([0, 2, 4])])

# Get elements that satisfy certain condition
print(X_flat > 15)
print(X_flat[X_flat > 15])

[51 55 14 19  0  4]
Elements of index 0, 2, 4:  [51 14  0]
[ True  True False  True False False]
[51 55 19]
